### ISSUE TITLE
Error: Invoked function failed - Cannot find module 'uuid/v4'

### ISSUE THREAD

**Issue by amicco** [gabehollombe-aws/step-functions-workshop#1]
I have received an **Error: Invoked function failed** with the message **Cannot find module 'uuid/v4'**:

```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'uuid/v4'",
    "trace": [
        "Runtime.ImportModuleError: Error: Cannot find module 'uuid/v4'",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
        "    at startup (internal/bootstrap/node.js:283:19)"
    ]
} 
```
I have the same issue reported here https://stackoverflow.com/questions/57906632/lambda-code-works-on-node-v8-10-but-not-nodejs-v10-x , it seems that with nodejs v10 I should add the library. I have solved creating an AWS Lambda layer with the library and adding reference in serverless.jml

**Comment by gabehollombe-aws** [comment]
@amicco - Could you please share where exactly you ran into this problem while following along with the workshop?  

The instructions at https://step-functions-workshop.go-aws.com/30_setting_up_our_services/20_creating_account_app_service.html  show to install the `uuid` npm module, so is it somewhere else, or did that install step not work?

**Comment by amicco** [comment]
@gabehollombe-aws I have followed the instructions reported at the link on an AWS Cloud9 environment (default Node.js v10) and the library `uuid` is not include in the deployed Lambda function, so I got the error. I can solve the issue adding the library or via _AWS Lambda Layers_ or via _package/include_ section in the `serverless.yml`.
I have further investigated and the issue does not occur if I switch my Cloud9 environment to Node.js v12. In this case the deployed Lambda function include the `uuid` library without any modification to `serverless.yml`.
It seems the issue is related to how dependencies are managed/included from Serverless Framework with different Node.js versions. Could you confirm that your dev environment is configured with Node.js v12?

**Comment by jeeslo** [comment]
I came across the same issue and it seems to be related to some breaking changes that were included in the latest version of the uuid library: https://www.npmjs.com/package/uuid#deep-requires-now-deprecated. No changes in the node package versions are required.

To fix it, you should replace the first line in the file _workshop-dir/account-applications/AccountApplications.js_, file as follows:
`const uuid = require('uuid/v4')`
for 
`const { v4: uuid } = require('uuid');`

Hope it helps.

**Comment by gabehollombe-aws** [comment]
@amicco  First, I want to apologize! Somehow I missed your reply on this thread. =-(  I'm so sorry for the delay here.

@jeeslo Thanks for this. I've deployed a new version to lock this to uuid@3.3.3 for now.
